### ISSUE TITLE
Add type info for Camera

### ISSUE THREAD

**Issue by davetapley** [hstern/pyspypoint#2]
To aid discoverability it would be nice to have types for `Camera`.

By manual inspection:

```
keys = 'activationDate', 'config', 'creationDate', 'dataMatrixKey', 'id', 'isCellular', 'lastPhoto', 'status', 'subscriptions', 'ucid', 'user']

config = 'name', 'batteryType', 'captureMode', 'dateFormat', 'delay', 'multiShot', 'sensibility', 'stamp', 'quality', 'temperatureUnit', 'timeFormat', 'transmitFreq', 'transmitFormat', 'transmitTime', 'schedule', 'transmitAuto', 'transmitUser', 'triggerSpeed', 'smallPicWidth'
```

**Comment by hstern** [comment]
Is there an API call that provides the information that you want? Everything from the cameras endpoint is already included in a Camera object.

**Comment by davetapley** [comment]
Not that I'm aware of. I was just thinking it would be useful to hard code some of the more common ones (e.g. `status`, `lastPhoto`, `name`), so autocomplete works in e.g. VS Code.

**Comment by hstern** [comment]
What is VS code doing for introspection? Is there a `__X__` attribute that we can set for it?

**Comment by davetapley** [comment]
I guess I should back up and show you what I'm doing 😁 

I have:
```python
client = spypoint.Client(user, password)
cameras = client.cameras()
c = next(iter(cameras))

cameraId = camera.id
cameraConfig = camera.config
```

And it shows:

![image](https://user-images.githubusercontent.com/48232/124694097-7804b580-de95-11eb-8043-1c25773c2e55.png)

---

I assume the `id` works because:

https://github.com/hstern/pyspypoint/blob/c383c72a93bdf2e430d2a3fb88a51dbf5b10de79/spypoint/client.py#L33

Perhaps assigning `config` in the same way might make it work?

**Comment by hstern** [comment]
That's an annoying feature of [Pylance](https://github.com/microsoft/pylance). Can you turn it off or can we give it hints so it does the right thing?

I did improve the code a bit so now you can reference `camera.config.name` or `photo.small.headers[0].name`. Please take a look at #3 and let me know if you have any further suggestions.

**Comment by davetapley** [comment]
Not sure r.e. Pylance. Kinda new to Python in VS Code 🤪 

I'm right on the limit of my Python knowledge, but #3 looks good insomuch as the tests show what I want 🙏🏻 

As an aside: Thanks for fast response, I should be able to contribute more once I get a bit more up to speed with Python.

**Comment by anthnyajp** [comment]
Here's all the config field settings that are provided by https://restapi.spypoint.com/api/v3/camera/all

An interesting field is "survivalMode". which according to spypoint: "After 4 consecutive missed communications, the device goes into survival mode, meaning it will only communicate every 24 hours. Turning the device OFF and then back ON resolves this issue. " Utilizing this API can help determine which cameras are in survival mode and will need to be reset. In most cases, the SD card needs to be reformatted. 

{
        "activationDate": "2022-02-01T18:32:03.981Z",
        "config": {
            "batteryType": "AA",
            "captureMode": "photo",
            "dateFormat": "mdy",
            "delay": "1min",
            "multiShot": 2,
            "name": "LINK-Stand-3",
            "operationMode": "standard",
            "quality": "normal",
            "schedule": [
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ],
                [
                    0,
                    0
                ]
            ],
            "sensibility": {
                "high": 9,
                "level": "high",
                "low": 35,
                "medium": 20
            },
            "smallPicWidth": 0,
            "stamp": true,
            "temperatureUnit": "F",
            "timeFormat": 12,
            "transmitAuto": true,
            "transmitFormat": "full",
            "transmitFreq": 2,
            "transmitTime": {
                "hour": 8,
                "minute": 0
            },
            "transmitUser": true,
            "triggerSpeed": "optimal"
        },
        "creationDate": "2022-02-01T18:32:03.981Z",
        "dataMatrixKey": "5KxxGNxxx",
        "hdSince": "2021-02-24T14:06:00.000Z",
        "id": "xxxx",
        "status": {
            "batteries": [
                70
            ],
            "batteryType": "AA",
            "capability": {
                "hdRequest": true,
                "jpegOptim": "0.00",
                "modemSdk": "quecopen-sdk-ec21a_1.0.0",
                "survivalMode": true
            },
            "installDate": "2022-11-20T16:32:00.000Z",
            "lastUpdate": "2023-04-16T20:00:00.000Z",
            "memory": {
                "size": 30416,
                "used": 204
            },
            "model": "LINK-MICRO-LTE-V",
            "modemFirmware": "EC21VFAR02A14M4G",
            "notifications": [],
            "serial": 0,
            "signal": {
                "bar": 2,
                "dBm": -116,
                "mcc": 311,
                "mnc": 480,
                "type": "LTE",
                "processed": {
                    "percentage": 50,
                    "bar": 2,
                    "lowSignal": false
                }
            },
            "sim": "xxxxxx",
            "temperature": {
                "unit": "F",
                "value": 59
            },
            "version": "V1.18.13-29 Rev:2"
        },
        "ucid": "xxxxxxx",
        "user": "xxxxxx",
        "isCellular": true,
        "subscriptions": [
            {
                "id": "",
                "cameraId": "xxxxxxxxxxxx",
                "paymentStatus": "active",
                "isActive": true,
                "plan": {
                    "name": "Basic",
                    "id": "Basic",
                    "isActive": true,
                    "isFree": true,
                    "isSelectable": true,
                    "photoCountPerMonth": 250,
                    "pricePerMonthIfPaidPerMonth": 5,
                    "pricePerMonthIfPaidAnnually": 4,
                    "pricePerYear": 48,
                    "pricePerMonthIfPaidAnnuallyInsidersClub": 0,
                    "pricePerMonthIfPaidPerMonthInsidersClub": 0,
                    "pricePerYearInsidersClub": 38.4,
                    "rebateIfPaidAnnually": 20,
                    "rebatePercentageInsidersClub": 20,
                    "showBanner": "insidersBasic",
                    "pricePerMonthIfPaidPerYear": 4,
                    "isUpgradable": true,
                    "isDowngradable": false
                },
                "currency": "USD",
                "paymentFrequency": "annual",
                "isFree": true,
                "startDateBillingCycle": "2022-12-04T23:01:48.765Z",
                "endDateBillingCycle": "2023-12-04T07:59:01.000Z",
                "monthEndBillingCycle": "2023-05-04T07:59:01.000Z",
                "photoCount": 150,
                "isAutoRenew": false
            }
        ],
        "ptpNotifications": []
    }


I also limited my script to only pull photos from certain cameras and only pictures of wild game and human activity using the https://restapi.spypoint.com/api/v3/photo/all api with the below in the request body. 


{"camera":["6036b1d060e47c9067bfzzzzz",
"6036b1d060e47c9067bfzzzzz",
"617e695533cf2d00187zzzzzz",
"6187e48f577bfb1f59zzzzzzzz",
"6194796b577bfb1zzzzzzzzzz",
"61b8eff119179300150zzzzzz",
"61e06600dcdaa700153zzzzz",
"61e06624e079b900175zzzzz",
"63b27154a6ba8d1azzzzzzz3",
"61ba4c8fd4f0ed00zzzzzzzzz",
"618edf6e9aa817001zzzzzzzz",
"618edf40af27880014zzzzzzz"],
"dateEnd":"2100-01-01T00:00:00.000Z",
"limit":10000,
"mediaTypes":[],"species":["buck","turkey","coyote","moose","bear","humanactivity","deer"]}

**Comment by De-Ge** [comment]
I have a few of these that go into survival mode very often, when I in-fact need them to stay on.. I'm not new to python, but am new to APIs.

- Sorry to necro this but was just looking into this API to see if this would solve that exact problem!

**Comment by hstern** [comment]
I’m going to close this issue. Please feel free to open up a new pull request or issue with your desired change.
